### ISSUE TITLE
Device registered, Device failed to be registered

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [TuyaAPI/cli#110]
I get his error when running the link command:
```
{ GotError: Invalid value "undefined" for header "access_token"
    at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at new ClientRequest (_http_client.js:203:14)
    at Object.request (https.js:289:10)
    at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:197:65) name: 'RequestError', code: 'ERR_HTTP_INVALID_HEADER_VALUE' }
```
The device still shows in the Tuya device list, but tuya-cli doesn't print out the localkey and seems to error out.

**Comment by loglux** [comment]
Have the same issue
```

[ { GotError: Invalid value "undefined" for header "access_token"
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
      at ClientRequest.setHeader (_http_outgoing.js:473:3)
      at new ClientRequest (_http_client.js:203:14)
      at Object.request (https.js:289:10)
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:197:65) name: 'RequestError', code: 'ERR_HTTP_INVALID_HEADER_VALUE' },
  { GotError: Invalid value "undefined" for header "access_token"
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
      at ClientRequest.setHeader (_http_outgoing.js:473:3)
      at new ClientRequest (_http_client.js:203:14)
      at Object.request (https.js:289:10)
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:197:65) name: 'RequestError', code: 'ERR_HTTP_INVALID_HEADER_VALUE' },
  { GotError: Invalid value "undefined" for header "access_token"
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
      at ClientRequest.setHeader (_http_outgoing.js:473:3)
      at new ClientRequest (_http_client.js:203:14)
      at Object.request (https.js:289:10)
      at get (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:197:65) name: 'RequestError', code: 'ERR_HTTP_INVALID_HEADER_VALUE' } ]

```

**Comment by codetheweb** [comment]
Combining with https://github.com/codetheweb/tuyapi/issues/411 for better visibility; please follow that issue for details.
