### ISSUE TITLE
Cannot Fetch using Wizard

### ISSUE THREAD

**Issue by danielgiovanni** [TuyaAPI/cli#114]
Use `DEBUG=true tuya-cli wizard`

and show this error
```
TypeError: Promise.all called on non-object
    at all (<anonymous>)
    at Function.any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/implementation.js:29:9)
    at any (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/promise.any/index.js:16:9)
    at list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:70:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an issue fetching that device. Make sure your account is linked and the ID is correct.
```

**Comment by pickonedev** [comment]
Same!

**Comment by JeremyKennedy** [comment]
I have the same issue. Here are some other reports of this: https://github.com/codetheweb/tuyapi/issues/432, https://github.com/codetheweb/tuyapi/issues/434

**Comment by codetheweb** [comment]
Consolidating issues, please follow https://github.com/codetheweb/tuyapi/issues/432 for updates.
