### ISSUE TITLE
Finished Step 5 but still encounter "fetching that device" error, Unable to Click **New Authorization

### ISSUE THREAD

**Issue by robinzhx** [TuyaAPI/cli#117]
I tried to run DEBUG output and it seems like the issue is related to Step 5. I did subscribed all 5 API Products but unable to refresh the Authorization Key since I can't find there is any refresh button for **New Authorization. 

[ Error: you don't have access to this API
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at process._tickCallback (internal/process/next_tick.js:68:7),
  Error: you don't have access to this API
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at process._tickCallback (internal/process/next_tick.js:68:7),
  Error: you don't have access to this API
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at process._tickCallback (internal/process/next_tick.js:68:7),
  Error: you don't have access to this API
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at process._tickCallback (internal/process/next_tick.js:68:7) ]

**Comment by robinzhx** [comment]
It leads to the issue with the frequent update UI of the tuya api site. I gonna make some info to update document.
