### ISSUE TITLE
Tuya Siren

### ISSUE THREAD

**Issue by leoheck** [TuyaAPI/cli#136]
Hi. I am trying to access a smart siren. And it looks like the data is pretty much encrypted. Do I have anything that I do to understand what I am receiving? What I want to do is to turn on and off the siren.

```
➜ DEBUG=* ./cli.js get --ip [IP] --id [ID] --key [KEY] --full
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to [IP]... +1ms
  TuyAPI Socket connected. +99ms
  TuyAPI GET Payload: +1ms
  TuyAPI {
  TuyAPI   gwId: '[ID]',
  TuyAPI   devId: '[ID]',
  TuyAPI   t: '1633904298',
  TuyAPI   dps: {},
  TuyAPI   uid: '[ID]'
  TuyAPI } +0ms
  TuyAPI Received data: 000055aa000000010000000a0000002c00000001f299f8c5b85a613b4db8bb577bceb2718c596ec9f7df20760a4290fbd0a1a2c383cb29440000aa55 +23ms
  TuyAPI Parsed: +1ms
  TuyAPI {
  TuyAPI   payload: '��ŸZa;M��W{βq�Yn��� v\nB��С��',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1
  TuyAPI } +0ms
  TuyAPI Received DATA packet +1ms
  TuyAPI Disconnect +0ms
��ŸZa;M��W{βq�Yn��� v
B��С��
  TuyAPI Socket closed: [IP] +1ms
```

**Comment by leoheck** [comment]
Maybe my issue is the version 3.3
 
```
  TuyAPI Received UDP message. +2s
  TuyAPI UDP data: +1ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.86.41',
  TuyAPI     gwId: 'ID',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'KEY',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  TuyAPI Received UDP message. +1ms
  TuyAPI UDP data: +0ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.86.41',
  TuyAPI     gwId: 'ID',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'KEY',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  TuyAPI Received UDP message. +2s
  TuyAPI UDP data: +0ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.86.242',
  TuyAPI     gwId: 'eb8aaaaefcc7d62c9fhg2c',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'KEY',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  TuyAPI Received UDP message. +1ms
  TuyAPI UDP data: +0ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.86.242',
  TuyAPI     gwId: 'eb8aaaaefcc7d62c9fhg2c',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'KEY',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  TuyAPI Received UDP message. +3s
  TuyAPI UDP data: +0ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.86.41',
  TuyAPI     gwId: 'ID',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'KEY',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  TuyAPI Received UDP message. +0ms
  TuyAPI UDP data: +1ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.86.41',
  TuyAPI     gwId: 'ID',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'KEY',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  TuyAPI Received UDP message. +2s
  TuyAPI UDP data: +0ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.86.242',
  TuyAPI     gwId: 'eb8aaaaefcc7d62c9fhg2c',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'KEY',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  TuyAPI Received UDP message. +0ms
  TuyAPI UDP data: +1ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.86.242',
  TuyAPI     gwId: 'eb8aaaaefcc7d62c9fhg2c',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'KEY',
  TuyAPI     version: '3.3'
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 19,
  TuyAPI   sequenceN: 0
  TuyAPI } +0ms
  ```

**Comment by leoheck** [comment]
If I try to set I receive this

```
 DEBUG=* tuya-cli set --ip 192.168.86.242 --id ID --key KEY --set "true" --protocol-version 3.3

  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.86.242... +3ms
  TuyAPI Socket connected. +72ms
  TuyAPI SET Payload: +1ms
  TuyAPI {
  TuyAPI   devId: 'ID',
  TuyAPI   gwId: 'ID',
  TuyAPI   uid: '',
  TuyAPI   t: 1633924441,
  TuyAPI   dps: { '1': true }
  TuyAPI } +0ms
  TuyAPI Received data: 000055aa00000001000000070000002c00000001bf0726de796c6ba96eab0c936f3fa9de7eb60fccd5698769a9d13e2d94499ccdbab4d4cd0000aa55 +34ms
  TuyAPI Parsed: +1ms
  TuyAPI {
  TuyAPI   payload: '�\u0007&�ylk�n�\f�o?��~�\u000f��i�i��>-�I��',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 7,
  TuyAPI   sequenceN: 1
  TuyAPI } +0ms
  TuyAPI Received DATA packet +0ms
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Timeout waiting for status response from device id: ID')
    at TuyaDevice.emit (events.js:303:17)
    at /usr/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:369:12
    at Timeout._onTimeout (/usr/lib/node_modules/@tuyapi/cli/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'Timeout waiting for status response from device id: ID'
}
```

**Comment by codetheweb** [comment]
No problem, happy to answer questions as they come up. 😃
