### ISSUE TITLE
There was an issue fetching that device. Make sure your account is linked and the ID is correct.

### ISSUE THREAD

**Issue by a1ex-ak** [TuyaAPI/cli#169]
```
[
  Error: 28841002: No permissions. Your subscription to cloud development plan has expired.
      at /usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:77:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.any (index 0)
      at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:64:28),
  Error: 28841107: No permission. The data center is suspended.Please go to the cloud development platform to enable the data center. 
      at /usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:77:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.any (index 1)
      at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:64:28),
  Error: GET_TOKEN_FAILED 2007, your ip(188.170.81.88) cross-region access is not allowed
      at TuyaOpenApiClient.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:123:35)
      at step (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:52:23)
      at Object.next (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:33:53)
      at fulfilled (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuya/tuya-connector-nodejs/lib/core/client.js:24:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5),
  Error: 28841107: No permission. The data center is suspended.Please go to the cloud development platform to enable the data center. 
      at /usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:77:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.any (index 3)
      at async list (/usr/local/lib/node_modules/@tuyapi/cli/lib/wizard.js:64:28)
]

```

**Comment by giauphan** [comment]
Please check your Data Center in your project and change the Region according to the following link.
``
https://developer.tuya.com/en/docs/iot/api-request?id=Ka4a8uuo1j4t4#title-1-Endpoints
``
