### ISSUE TITLE
tuya-cli list-app error

### ISSUE THREAD

**Issue by legolass73** [TuyaAPI/cli#17]
Waiting for request...error happened in proxy websocket: { Error: listen EADDRINUSE: address already in use :::8001                                                                                      
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)                                                                                                                                              
    at listenInCluster (net.js:1327:12)                                                                                                                                                                     
    at Server.listen (net.js:1414:7)                                                                                                                                                                        
    at async.series.tipText (/usr/local/lib/node_modules/anyproxy/proxy.js:205:32)                                                                                                                          
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:607:21                                                                                                                          
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:246:17                                                                                                                          
    at iterate (/usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:146:13)                                                                                                                
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:157:25                                                                                                                          
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:248:21                                                                                                                          
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:612:34                                                                                                                          
    at async.series.tipText (/usr/local/lib/node_modules/anyproxy/proxy.js:200:11)                                                                                                                          
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:607:21                                                                                                                          
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:246:17                                                                                                                          
    at iterate (/usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:146:13)                                                                                                                
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:157:25                                                                                                                          
    at /usr/local/lib/node_modules/anyproxy/node_modules/async/lib/async.js:248:21

**Comment by codetheweb** [comment]
Several things could be happening.  The most likely is that you have a duplicate instance of `tuya-cli list-app` running in the background, still bound to the port.  The other possibility is that you have a completely different process bound to 8001.

In any case, I'd try restarting first.  If that doesn't fix it, you can pass a new (random) port with the `-p` flag: `tuya-cli list-app -p 8574`.
