### ISSUE TITLE
List-App throws JSON Parse Error

### ISSUE THREAD

**Issue by AndreAuth** [TuyaAPI/cli#26]
Hello,

in the new Version i get an JSON Parse Error when i try to list my smartlife devices.

I have got an IPhone.

Here is the error :

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\Andre\AppData\Roaming\npm\node_modules\@tuyapi\cli\lib\list-app.js:28:23
    at C:\Users\Andre\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\http-mitm-proxy\lib\proxy.js:1047:12
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\async\dist\async.js:3110:16
    at eachOfArrayLike (C:\Users\xxx\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\async\dist\async.js:1069:9)
    at eachOf (C:\Users\xxx\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\async\dist\async.js:1117:5)
    at Object.eachLimit (C:\Users\xxx\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\async\dist\async.js:3172:5)
    at Proxy._onResponseData (C:\Users\xxx\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\http-mitm-proxy\lib\proxy.js:1046:9)
    at ProxyFinalResponseFilter.write (C:\Users\xxx\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\http-mitm-proxy\lib\proxy.js:875:11)
    at IncomingMessage.ondata (_stream_readable.js:722:22)

**Comment by codetheweb** [comment]
Are you using the Tuya Smart app or some other white-labeled app?  I've only tested this tool with the Tuya Smart app and don't plan on providing support for or testing it with other apps.

**Comment by AndreAuth** [comment]
I have used a white-labeled one and the tuya app.

I think i might know what causes the problem.

As soon as i add this bulb to my tuya app i get the error:

https://www.amazon.de/gp/product/B07PV5LBCZ/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

All other tuya devices i have are working fine.

**Comment by codetheweb** [comment]
Please update the CLI tool to v1.8.2 and try again; I just pushed an update that I think will fix this.

**Comment by AndreAuth** [comment]
I tried it. No it doesn't work. Now it wont show any error or any json output. It still says: waiting for request and nothing happens.

**Comment by ptrWe** [comment]
> I tried it. No it doesn't work. Now it wont show any error or any json output. It still says: waiting for request and nothing happens.

Have the same issue with version 1.8.3 and had the same JSON Parse Error with the previous version.

**Comment by codetheweb** [comment]
Please update to v1.8.4 and try again. Just shipped a patch that should fix this issue.

**Comment by codetheweb** [comment]
Another user reported the update fixed this problem.

If either of you continue to have issues, please reopen this.
