### ISSUE TITLE
tuya-cli on OpenWrt -> Error.

### ISSUE THREAD

**Issue by puppinoo** [TuyaAPI/cli#58]
Hi,
I tried to install tuya-cli on my Lede router. installation went fine but when I try to launch it I receive this error. Any advice?

Regards.
Pino.

`tuya-cli 
internal/util.js:214
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at Object.promisify (internal/util.js:214:11)
at Object.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/get-response.js:8:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:13:24)

`

**Comment by codetheweb** [comment]
I'm guessing your Node.js version is too old.  What's the output of `node -v`?

**Comment by puppinoo** [comment]
> I'm guessing your Node.js version is too old. What's the output of `node -v`?

node -v
v8.16.0

**Comment by puppinoo** [comment]
You were right. I updated my node version to v12.14.1 and now everythong seems to work.

Thanks a lot for your amazin work (I also add that installing stuff on routers with custom firmwares is amazing btw).

Regards.
Pino.

**Comment by codetheweb** [comment]
👍
